import { ClassifiedEmail, RawEmail, DashboardStats } from './types';

const mockRawEmails: RawEmail[] = [
  {
    id: '1',
    user_id: 'user1',
    subject: 'Python Developer Interview - TechCorp',
    sender: 'hr@techcorp.com',
    body: 'Dear Candidate, We are pleased to invite you for an interview for the Python Developer position at TechCorp. The interview is scheduled for February 28, 2026 at 2:00 PM. Required skills include Python, React, SQL, and AWS. Location: Remote. Experience: 2-4 years.',
    date_received: '2026-02-27T10:00:00Z',
    gmail_id: 'gmail1',
    created_at: '2026-02-27T10:00:00Z',
  },
  {
    id: '2',
    user_id: 'user1',
    subject: 'Team Meeting Friday',
    sender: 'manager@company.com',
    body: 'Hi Team, Please join our weekly team meeting on Friday, February 28, 2026 at 3:00 PM. We will discuss project updates and upcoming deadlines. Meeting Link: https://meet.google.com/abc-defg-hij',
    date_received: '2026-02-26T14:00:00Z',
    gmail_id: 'gmail2',
    created_at: '2026-02-26T14:00:00Z',
  },
  {
    id: '3',
    user_id: 'user1',
    subject: 'Full Stack Developer Position - StartupXYZ',
    sender: 'careers@startupxyz.com',
    body: 'We are looking for a Full Stack Developer to join our team. Skills required: JavaScript, TypeScript, Node.js, React, MongoDB. Location: Bangalore. Experience: 3-5 years. Deadline: March 15, 2026.',
    date_received: '2026-02-25T09:00:00Z',
    gmail_id: 'gmail3',
    created_at: '2026-02-25T09:00:00Z',
  },
  {
    id: '4',
    user_id: 'user1',
    subject: 'Exclusive Sale - 50% Off!',
    sender: 'promotions@shop.com',
    body: 'Limited time offer! Get 50% off on all items. Shop now and save big!',
    date_received: '2026-02-24T08:00:00Z',
    gmail_id: 'gmail4',
    created_at: '2026-02-24T08:00:00Z',
  },
  {
    id: '5',
    user_id: 'user1',
    subject: 'Project Deadline Reminder',
    sender: 'project-manager@company.com',
    body: 'This is a reminder that the project deadline is approaching on March 5, 2026. Please ensure all deliverables are completed on time.',
    date_received: '2026-02-23T11:00:00Z',
    gmail_id: 'gmail5',
    created_at: '2026-02-23T11:00:00Z',
  },
  {
    id: '6',
    user_id: 'user1',
    subject: 'React Developer - Remote Opportunity',
    sender: 'recruiter@techcompany.com',
    body: 'Great opportunity for React Developer. Skills: React, TypeScript, Redux, Next.js. Location: Remote. Salary: Competitive. Apply by: March 10, 2026.',
    date_received: '2026-02-22T10:30:00Z',
    gmail_id: 'gmail6',
    created_at: '2026-02-22T10:30:00Z',
  },
  {
    id: '7',
    user_id: 'user1',
    subject: 'Tech Conference 2026 - Register Now',
    sender: 'events@techconf.com',
    body: 'Join us for Tech Conference 2026 on March 20-22, 2026 in San Francisco. Early bird registration ends March 1st. Register at: https://techconf.com/register',
    date_received: '2026-02-21T15:00:00Z',
    gmail_id: 'gmail7',
    created_at: '2026-02-21T15:00:00Z',
  },
  {
    id: '8',
    user_id: 'user1',
    subject: 'Banking Statement - January 2026',
    sender: 'noreply@bank.com',
    body: 'Your banking statement for January 2026 is now available. Please log in to view your statement.',
    date_received: '2026-02-20T07:00:00Z',
    gmail_id: 'gmail8',
    created_at: '2026-02-20T07:00:00Z',
  },
];

export const mockClassifiedEmails: ClassifiedEmail[] = [
  {
    id: '1',
    user_id: 'user1',
    raw_email_id: '1',
    category: 'job',
    priority: 'high',
    spam_score: 0.1,
    job_title: 'Python Developer',
    company: 'TechCorp',
    location: 'Remote',
    experience_level: '2-4 years',
    skills: ['Python', 'React', 'SQL', 'AWS'],
    application_deadline: '2026-03-05T23:59:59Z',
    event_title: 'Python Developer Interview',
    event_date: '2026-02-28T14:00:00Z',
    event_location: 'Online',
    organizer: 'hr@techcorp.com',
    meeting_link: 'https://meet.google.com/tech-corp-interview',
    reminder_set: true,
    created_at: '2026-02-27T10:00:00Z',
    raw_email: mockRawEmails[0],
  },
  {
    id: '2',
    user_id: 'user1',
    raw_email_id: '2',
    category: 'event',
    priority: 'medium',
    spam_score: 0.05,
    event_title: 'Team Meeting Friday',
    event_date: '2026-02-28T15:00:00Z',
    event_location: 'Online',
    organizer: 'manager@company.com',
    meeting_link: 'https://meet.google.com/abc-defg-hij',
    reminder_set: true,
    created_at: '2026-02-26T14:00:00Z',
    raw_email: mockRawEmails[1],
  },
  {
    id: '3',
    user_id: 'user1',
    raw_email_id: '3',
    category: 'job',
    priority: 'high',
    spam_score: 0.08,
    job_title: 'Full Stack Developer',
    company: 'StartupXYZ',
    location: 'Bangalore',
    experience_level: '3-5 years',
    skills: ['JavaScript', 'TypeScript', 'Node.js', 'React', 'MongoDB'],
    application_deadline: '2026-03-15T23:59:59Z',
    created_at: '2026-02-25T09:00:00Z',
    raw_email: mockRawEmails[2],
  },
  {
    id: '4',
    user_id: 'user1',
    raw_email_id: '4',
    category: 'spam',
    priority: 'low',
    spam_score: 0.95,
    created_at: '2026-02-24T08:00:00Z',
    reminder_set: false,
    raw_email: mockRawEmails[3],
  },
  {
    id: '5',
    user_id: 'user1',
    raw_email_id: '5',
    category: 'important',
    priority: 'high',
    spam_score: 0.02,
    event_title: 'Project Deadline',
    event_date: '2026-03-05T23:59:59Z',
    reminder_set: true,
    created_at: '2026-02-23T11:00:00Z',
    raw_email: mockRawEmails[4],
  },
  {
    id: '6',
    user_id: 'user1',
    raw_email_id: '6',
    category: 'job',
    priority: 'high',
    spam_score: 0.1,
    job_title: 'React Developer',
    company: 'TechCompany',
    location: 'Remote',
    experience_level: '2-5 years',
    skills: ['React', 'TypeScript', 'Redux', 'Next.js'],
    application_deadline: '2026-03-10T23:59:59Z',
    created_at: '2026-02-22T10:30:00Z',
    raw_email: mockRawEmails[5],
  },
  {
    id: '7',
    user_id: 'user1',
    raw_email_id: '7',
    category: 'event',
    priority: 'medium',
    spam_score: 0.15,
    event_title: 'Tech Conference 2026',
    event_date: '2026-03-20T09:00:00Z',
    event_location: 'San Francisco',
    organizer: 'events@techconf.com',
    meeting_link: 'https://techconf.com/register',
    reminder_set: false,
    created_at: '2026-02-21T15:00:00Z',
    raw_email: mockRawEmails[6],
  },
  {
    id: '8',
    user_id: 'user1',
    raw_email_id: '8',
    category: 'important',
    priority: 'medium',
    spam_score: 0.05,
    created_at: '2026-02-20T07:00:00Z',
    reminder_set: false,
    raw_email: mockRawEmails[7],
  },
];

export const mockDashboardStats: DashboardStats = {
  total: 127,
  jobs: 5,
  events: 3,
  important: 12,
  spam: 45,
};

export const mockUser = {
  id: 'user1',
  email: 'student@college.edu',
  last_sync: '2026-02-27T12:30:00Z',
  created_at: '2026-01-15T10:00:00Z',
};
